//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplikacijaZaZeljeznickuStanicuDRAOS2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AplikacijaZaZeljeznickuStanicuDRAOS2.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of passengers.
        /// </summary>
        public static string BrojPutnika {
            get {
                return ResourceManager.GetString("BrojPutnika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date od departure.
        /// </summary>
        public static string DatumPolaska {
            get {
                return ResourceManager.GetString("DatumPolaska", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival.
        /// </summary>
        public static string Dolazak {
            get {
                return ResourceManager.GetString("Dolazak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Engleski {
            get {
                return ResourceManager.GetString("Engleski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entering the date and time of travel.
        /// </summary>
        public static string groupUnosDIV {
            get {
                return ResourceManager.GetString("groupUnosDIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data entry.
        /// </summary>
        public static string groupUnosPodataka {
            get {
                return ResourceManager.GetString("groupUnosPodataka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At the form named step 1 you can see trains scedules.
        /// </summary>
        public static string helpSadrzajKorak1 {
            get {
                return ResourceManager.GetString("helpSadrzajKorak1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the form of step 2, you can enter data on the desired destination.
        /// </summary>
        public static string helpSadrzajKorak2 {
            get {
                return ResourceManager.GetString("helpSadrzajKorak2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the form of step 3, you can enter the time, date and class with which you want to travel.
        /// </summary>
        public static string helpSadrzajKorak3 {
            get {
                return ResourceManager.GetString("helpSadrzajKorak3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the form of step 4 shows the method of payment cards.
        /// </summary>
        public static string helpSadrzajKorak4 {
            get {
                return ResourceManager.GetString("helpSadrzajKorak4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Buy a ticket to continue to next step.
        /// </summary>
        public static string helpSadrzajKupiKartu {
            get {
                return ResourceManager.GetString("helpSadrzajKupiKartu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string Klasa {
            get {
                return ResourceManager.GetString("Klasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1.
        /// </summary>
        public static string Korak1 {
            get {
                return ResourceManager.GetString("Korak1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2.
        /// </summary>
        public static string Korak2 {
            get {
                return ResourceManager.GetString("Korak2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3.
        /// </summary>
        public static string Korak3 {
            get {
                return ResourceManager.GetString("Korak3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 4.
        /// </summary>
        public static string Korak4 {
            get {
                return ResourceManager.GetString("Korak4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy a ticket.
        /// </summary>
        public static string KupiKartu {
            get {
                return ResourceManager.GetString("KupiKartu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Naprijed {
            get {
                return ResourceManager.GetString("Naprijed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string Njemacki {
            get {
                return ResourceManager.GetString("Njemacki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One person.
        /// </summary>
        public static string Pojedinacna {
            get {
                return ResourceManager.GetString("Pojedinacna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departing from.
        /// </summary>
        public static string PolazakIz {
            get {
                return ResourceManager.GetString("PolazakIz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Ponisti {
            get {
                return ResourceManager.GetString("Ponisti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string Porodicna {
            get {
                return ResourceManager.GetString("Porodicna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrivals and departures in the next 2 hours.
        /// </summary>
        public static string TEST {
            get {
                return ResourceManager.GetString("TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        public static string Turski {
            get {
                return ResourceManager.GetString("Turski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of arrival.
        /// </summary>
        public static string VrijemeDolaska {
            get {
                return ResourceManager.GetString("VrijemeDolaska", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of departure.
        /// </summary>
        public static string VrijemePolaska {
            get {
                return ResourceManager.GetString("VrijemePolaska", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket type.
        /// </summary>
        public static string VrstaKarte {
            get {
                return ResourceManager.GetString("VrstaKarte", resourceCulture);
            }
        }
    }
}
